# Frieren Theme - Ghostty Terminal

background = e3eadf
foreground = 1d2837
selection-background = 2b4e55
selection-foreground = e3eadf
cursor-color = 2b4e55

palette = 0=#334247
palette = 1=#61727a
palette = 2=#4b775e
palette = 3=#6b8276
palette = 4=#2b4e55
palette = 5=#395857
palette = 6=#436961
palette = 7=#d4ddd0
palette = 8=#475a58
palette = 9=#909a9a
palette = 10=#6d9471
palette = 11=#a1b99c
palette = 12=#61727a
palette = 13=#6b8276
palette = 14=#909a9a
palette = 15=#e3eadf
