# Frieren Theme - Hyprland Colors

general {
    col.active_border   = rgba(2b4e55ff) rgba(4b775eff) 45deg
    col.inactive_border = rgba(909a9a55)
}

decoration {
    shadow {
        color          = rgba(1d283780)
        color_inactive = rgba(1d283740)
    }
}
