# Frieren Theme - Kitty Terminal

background            #e3eadf
foreground            #1d2837
selection_background  #2b4e55
selection_foreground  #e3eadf
cursor                #2b4e55
cursor_text_color     #e3eadf
url_color             #4b775e

# Black
color0  #334247
color8  #475a58

# Red
color1  #61727a
color9  #395857

# Green
color2  #4b775e
color10 #6d9471

# Yellow
color3  #6b8276
color11 #a1b99c

# Blue (accent)
color4  #2b4e55
color12 #61727a

# Magenta
color5  #395857
color13 #6b8276

# Cyan
color6  #436961
color14 #909a9a

# White
color7  #d4ddd0
color15 #e3eadf
