# Frieren Theme - Mako Notifications

background-color=#e3eadfee
text-color=#1d2837
border-color=#2b4e55
progress-color=over #4b775e

[urgency=low]
background-color=#d4ddd0ee
border-color=#909a9a

[urgency=normal]
background-color=#e3eadfee
border-color=#2b4e55

[urgency=high]
background-color=#e3eadfee
border-color=#395857
text-color=#1d2837
